---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
library(dplyr)
library(tidyr)
library(modelsummary)
library(glue)
library(gt)
library(car)
library(dunn.test)
library(rcompanion)
library(rstatix)
library(purrr)
library(ggplot2)
library(patchwork)
library(psych)
library(performance)
library(lmtest)
library(readxl)
library(openxlsx)
library(pheatmap)
library(randomForest)
```

```{r}
data = read.csv("data/datafinal.csv")
```

```{r}
mod1 = lm(HB ~ RBC..106.µL., data = data)
mod2 = lm(HB ~ RBC..106.µL. + PV.ml. , data = data)
mod3 = lm(HB ~ RBC..106.µL. + PV.ml. + Altitude, data = data)
mod4 = lm(HB ~ RBC..106.µL. * Altitude + PV.ml. * Altitude, data = data)
mod5 = lm(HB ~ RBC..106.µL. * Altitude + PV.ml. * Altitude * Sexe_F_Fille_G_Garçon, data = data)
models = list(mod1, mod2, mod3, mod4, mod5)
modelsummary(models, stars = T, statistic = NULL)
```

```{r}
mod1 = lm(HCT.. ~ RBC..106.µL., data = data)
mod2 = lm(HCT.. ~ RBC..106.µL. + PV.ml. , data = data)
mod3 = lm(HCT.. ~ RBC..106.µL. + PV.ml. + Altitude, data = data)
mod4 = lm(HCT.. ~ RBC..106.µL. * Altitude + PV.ml. * Altitude, data = data)
mod5 = lm(HCT.. ~ RBC..106.µL. * Altitude + PV.ml. * Altitude * Sexe_F_Fille_G_Garçon, data = data)
models = list(mod1, mod2, mod3, mod4, mod5)
modelsummary(models, stars = T, statistic = NULL)
```

