```{r}
library(dplyr)
library(tidyr)
library(modelsummary)
library(glue)
library(gt)
library(car)
library(dunn.test)
library(rcompanion)
library(rstatix)
library(purrr)
library(ggplot2)
library(patchwork)
library(psych)
library(performance)
library(lmtest)
library(readxl)
library(openxlsx)
library(pheatmap)
library(randomForest)
```

```{r}
diag = read.csv("data/diags.csv")
nutri = read.csv("data/nutri.csv")
diag = diag[,-c(1,3)]
data = left_join(diag, nutri, by = c("Code_Sujet", "Age_mois", "Age_categorie_binaire"))
```

```{r}
data_long <- data %>%
  pivot_longer(
    cols = starts_with("Anemie_") | starts_with("Polyglobulie_"),
    names_to = "Diagnostic",
    values_to = "Valeur"  # oui / non / NA
  ) %>%
  filter(!is.na(Valeur))  # tu peux choisir de garder ou non les NA
```

```{r}
data_long %>%
  group_by(Diagnostic, Valeur) %>%
  summarise(
    moy_fer = mean(Fer..mg.100.g., na.rm = TRUE),
    moy_calories = mean(kCalHors.fibres, na.rm = TRUE),
    n = n()
  )
```

```{r}
ggplot(data_long, aes(x = Valeur, y = Fer..mg.100.g.)) +
  geom_boxplot() +
  facet_wrap(~ Diagnostic, scales = "free_y") +
  labs(title = "Apport en fer selon chaque critère de diagnostic")
```
```{r}
library(dplyr)
library(purrr)

# Split les données et récupère les noms des groupes
groupes <- data_long %>% group_split(Diagnostic)
noms_groupes <- data_long %>% group_by(Diagnostic) %>% pull(Diagnostic)

# Applique le modèle avec affichage du nom du Diagnostic
imap(groupes, ~ {
  cat("\n==== Résultats pour le Diagnostic :", noms_groupes[[.y]], "====\n")
  print(summary(lm(Fer..mg.100.g. ~ Valeur, data = .x)))
})
```

```{r}
mod1_3ans = lm(Fer..mg.100.g. ~ Diagnostic * Valeur, data = data_long)
mod2_3ans = lm(kCalHors.fibres ~ Diagnostic * Valeur, data = data_long)

summary(mod1)
summary(mod2)
```
```{r}
mod = lm(Fer..mg.100.g. ~ Polyglobulie_14.5_OMS2024, data = data)
summary(mod)
qqPlot(mod)
```
```{r}
data_subset <- data %>%
  select(Fer..mg.100.g., kCalHors.fibres, Anemie_OMS2011, Anemie_OMS2024, Anemie_SD, Anemie_2SD, Anemie_Q10, Anemie_2SD_Hbmass_kg, Anemie_Q10_Hbmass, Polyglobulie_14.5_OMS2011, Polyglobulie_14.5_OMS2024, Polyglobulie_SD, Polyglobulie_2SD, Polyglobulie_Q90, Polyglobulie_SD_Hbmass_kg, Polyglobulie_2SD_Hbmass_kg, Polyglobulie_Q90_Hbmass)
data_subset_all <- na.omit(data_subset)
mod = randomForest(Fer..mg.100.g. ~ ., data = data_subset_all[,-2], importance = TRUE)
varImpPlot(mod)
```


